version: '3.4'

services:
  queue:
    image: gavinmroy/alpine-rabbitmq-autocluster
    networks:
      - rook_private_net
      - rook_public_net
 #   ports:
#      - "15672:15672"
    #volumes:
      #- rabbit_vol:/var/lib/rabbitmq/mnesia
    environment:
      - AUTOCLUSTER_TYPE=consul 
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_SVC=rabbitmq
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - RABBITMQ_ERLANG_COOKIE=secrect
    deploy:
      labels:
        traefik.docker.network: rook_public_net
        traefik.frontend.rule: "Host:queue.dev.mab.scot"
        traefik.port: "15672"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role!=manager
      resources:
        limits:
          cpus: '0.75'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 256M 

  consul:
    image: progrium/consul
    networks:
      - rook_private_net
    ports:
      - "8500:8500"
    environment:
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_LOCAL_CONFIG={'skip_leave_on_interrupt': true}"
    entrypoint:
      - consul
      - agent
      - -server
      - -ui-dir=/ui
      - -client=0.0.0.0
      - -bootstrap-expect=1
      - -retry-join=consul
      - -data-dir=/agent-data 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role!=manager
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M 

networks:
  rook_private_net:
    external: true
  rook_public_net:
    external: true

volumes:
  rabbit_vol:
    name: rabbit_vol-1
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 2
      iops: 1000
      backing: relocatable