version: "3.3"

services:

  scalingservice:
    image: rookframework/rook-platform-scaling:1.18.1.94
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        prometheus.enable: "true"
        prometheus.port: "80"
        prometheus.path: "/metrics"
        prometheus.job: "${ENVIRONMENT}_scalingservice"        
      placement:
        constraints:
          - node.role == manager		  
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 256M
    networks:
      - rook_private_net

  relationshipservice:
    image: rookframework/rook-platform-relationship:1.6.1.94
    environment:
      - LOGLEVEL
      - FQDSN=${FQDSN}
    networks:
      - rook_private_net
    deploy:
      mode: replicated
      replicas: 2
      labels:
        prometheus.enable: "true"
        prometheus.port: "80"
        prometheus.path: "/metrics"
        prometheus.job: "${ENVIRONMENT}_relationshipservice"
      resources:
        limits:
          cpus: '0.40'
          memory: 1024M
        reservations:
          cpus: '0.20'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  organisationservice:
    image: rookframework/rook-platform-organisation:1.3.1.94
    environment:
      - MONGODATABASEURI
      - MONGODATABASENAME
      - LOGLEVEL
      - FQDSN=${FQDSN}
    networks:
      - rook_private_net
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      labels:
        prometheus.enable: "true"
        prometheus.port: "80"
        prometheus.path: "/metrics"
        prometheus.job: "${ENVIRONMENT}_organisationservice"
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - organisationmongo

  userservice:
    image: rookframework/rook-platform-user:1.9.1.94
    environment:
      - MONGODATABASEURI
      - MONGODATABASENAME
      - LOGLEVEL      
      - FQDSN=${FQDSN}
    networks:
      - rook_private_net
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      labels:
        prometheus.enable: "true"
        prometheus.port: "80"
        prometheus.path: "/metrics"
        prometheus.job: "${ENVIRONMENT}_userservice"
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - usermongo


  organisationapi:
    image: rookframework/rook-platform-organisationapi:1.4.1.94
    environment:
      - IDENTITYSERVERADDRESS
      - LOGLEVEL
      - ORGANISATIONCACHETIMEOUT
      - BASEURL
      - FQDSN=${FQDSN}
      - REQUIRESAUTHORISATION
      - REQUIRESJWTVALIDATION
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      labels:
        - "prometheus.enable=true"
        - "prometheus.port=80"
        - "prometheus.path=/metrics"
        - "prometheus.job=${ENVIRONMENT}_organisationapi"
        - traefik.frontend.rule=Host:organisationapi.${DOMAIN}
        - traefik.enable=true
        - traefik.port=15672
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https 
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - rook_private_net
      - traefik-public

  userapi:
    image: rookframework/rook-platform-userapi:1.5.1.94
    environment:
      - IDENTITYSERVERADDRESS
      - LOGLEVEL
      - ORGANISATIONCACHETIMEOUT
      - BASEURL
      - FQDSN=${FQDSN}
      - REQUIRESAUTHORISATION
      - REQUIRESJWTVALIDATION
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      labels:
        - "prometheus.enable=true"
        - "prometheus.port=80"
        - "prometheus.path=/metrics"
        - "prometheus.job=${ENVIRONMENT}_userapi"
        - traefik.frontend.rule=Host:userapi.${DOMAIN}
        - traefik.enable=true
        - traefik.port=15672
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https 
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - rook_private_net
      - traefik-public

  relationshippostgres:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=pass
    networks:
      rook_private_net:
        aliases:
          - relationshippostgres
    volumes:
      - relationshippostgresvolume:/var/lib/postgresql
    deploy:
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.40'
          memory: 2048M
        reservations:
          cpus: '0.20'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  usermongo:
    image: mongo
    command: --smallfiles
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rook
      MONGO_INITDB_ROOT_PASSWORD: rook
    networks:
      rook_private_net:
        aliases:
          - usermongo

  organisationmongo:
    image: mongo
    command: --smallfiles
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rook
      MONGO_INITDB_ROOT_PASSWORD: rook
    networks:
      rook_private_net:
        aliases:
          - organisationmongo


networks:
  rook_private_net:
    external: true
  traefik-public:
    external: true


volumes:
  relationshippostgresvolume:
    driver: "cloudstor:aws"
    driver_opts:
      ebstype: gp2
      size: 2
      iops: 1000
      backing: relocatable