version: "3"

services:
 visualiser:
   image: dockersamples/visualizer
   volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
   ports:
   - "8081:8080"
   environment:
      - VIRTUAL_HOST=vis.dev.mab.scot
      - ZONE=dev.mab.scot
   networks:
      - rook_public_net
   deploy:
      placement:
        constraints:
          - node.role==manager