version: "3"

services:
 visualiser:
   image: visualiser
   volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
   expose:
   - "8080"
   environment:
      - VIRTUAL_HOST=vis.dev.mab.scot
      - ZONE=dev.mab.scot
   deploy:
      placement:
        constraints:
          - node.role==manager